<?php

/**
 * Securely redirects to a URL within the application.
 * It now validates that the URL starts with your APP_LINK.
 *
 *
 * @param string $url The full URL to redirect to, generated by route().
 */




function safeRedirect($url) {
    // Validate that the redirect URL is part of your application
    if (strpos($url, APP_LINK) !== 0) {
        // If not, default to a safe location (dashboard)
        $url = route('dashboard');
    }
    header("Location: " . $url);
    exit();
}

// --- Authentication Status ---
function isLoggedIn() {
    return isset($_SESSION['user_id']) && is_numeric($_SESSION['user_id']);
}

function isAdmin() {
    return isset($_SESSION['role']) && $_SESSION['role'] === 'admin';
}

function isHR() {
    return isset($_SESSION['role']) && $_SESSION['role'] === 'hr';
}

function isAdminOrHR() {
    return isAdmin() || isHR();
}

function isEmployee() {
    return isset($_SESSION['role']) && $_SESSION['role'] === 'employee';
}

function getCurrentUserId() {
    return isset($_SESSION['user_id']) && is_numeric($_SESSION['user_id']) ? (int)$_SESSION['user_id'] : null;
}

// --- Redirection Functions (Using route()) ---

function redirectIfNotAdminOrHR() {
    if (!isAdminOrHR()) {
        $_SESSION['redirect_url'] = $_SERVER['REQUEST_URI'] ?? route('dashboard');
        safeRedirect(APP_LINK .'/employee/');
    }
}

function redirectIfNotLoggedIn() {
    if (!isLoggedIn()) {
        $_SESSION['redirect_url'] = $_SERVER['REQUEST_URI'] ?? route('dashboard');
        safeRedirect(Proute('login'));
    }
}

function redirectIfNotAdmin() {
    redirectIfNotLoggedIn();
    if (!isAdmin()) {
        safeRedirect(Proute('employee')); // Assumes you have an 'employee_dashboard' route
    }
}
function redirectIfAdminorHR() {
    redirectIfNotLoggedIn();
    // Allow Admins to access HR pages
    if (isHR() || isAdmin()) {
        safeRedirect(route('dashboard'));
    }
}

function redirectIfNotHR() {
    redirectIfNotLoggedIn();
    // Allow Admins to access HR pages
    if (!isHR() && !isAdmin()) {
        safeRedirect(Proute('employee'));
    }
}

/**
 * Handles user logout by clearing the session and redirecting to the login page.
 */
function handleLogout() {
    // Unset all of the session variables
    $_SESSION = [];

    // Destroy the session
    if (ini_get("session.use_cookies")) {
        $params = session_get_cookie_params();
        setcookie(session_name(), '', time() - 42000,
            $params["path"], $params["domain"],
            $params["secure"], $params["httponly"]
        );
    }
    session_destroy();

    // Redirect to the login page using the full link
    safeRedirect(APP_LINK . '/index.php?route=login');
}
?>